### PR TITLE
ofParameter name change improvements

### PR DESCRIPTION
**Pull request by roymacdonald**
Hey @eduardfrigola 
Look at the changes I've done. As we discussed https://github.com/openframeworks/openFrameworks/issues/6576
I also added an ofEvent that gets notified when the name changes so any gui can update automagically. 

I am testing and works fine

I think that if we get this merged into master then we should go for the ofxGui improvement so it listens to the name change.

### CODE REVIEW

**Comment by eduardfrigola** [comment]
Hi @roymacdonald 
Thanks for the changes.
I have tested them with my use case and works as expected!

Having static function in `ofParameterGroup` makes everything very clear, that is nice!

Should it be another event, sent by `ofParameterGroup`, that tells if any parameter has changed name, similar to `parameterChangedE()`? If not you should need a listener for each parameter you have in the gui (thinking about adding this to ofxGui)

**Comment by roymacdonald** [comment]
Hi, 
right, there should be something like `parameterChangedE()` but for the name change. Although I already implemented ofxGui with listeners for the name changes. I think that there would be just as much extra lines of codes if I would use an event triggered by `ofParameterGroup` instead of each `ofParameter`.
I'll add anyways the event for the `ofParameterGroup`

**Comment by roymacdonald** [comment]
@eduardfrigola I added an event in ofParameterGroup that is triggered when any of its children change name. Also implemented in ofxGui.

**Comment by eduardfrigola** [comment]
Nice!
Thanks Roy!

Should I merge this and pr this branch to main repo?

**Comment by roymacdonald** [comment]
> Should I merge this and pr this branch to main repo?

Yes.

**Pull request merged**
